#!/bin/sh
#
# This shell script scans the opcodes.h file (which is itself generated by
# another shell script) and the vdbe.c file, and uses the information gleaned
# to create the opcodes.c source file.
#
# Opcodes.c contains strings which are the symbolic names for the various
# opcodes used by the VDBE, and a function that gives the synopsis of an
# instruction.  These are used when disassembling a VDBE program during
# tracing or as a result of the EXPLAIN keyword.
#
# Usage: mkopcodec.sh opcodes.h vdbe.c

printf '%s\n' "/* Automatically generated.  Do not edit */"
printf '%s\n' "/* See the tool/mkopcodec.sh script for details. */"
printf '%s\n' "#include \"sqlInt.h\""
printf '%s\n' "#include \"vdbeInt.h\""
printf '%s\n' "const char *sqlOpcodeName(int i){"
printf '%s\n' " static const char *const azName[] = {"
mx=0

set -eu  # Strict shell (w/o -x and -o pipefail)
set -f   # disable pathname expansion

# The loops below change the positional parameters.
opcodes_h="$1"
vdbe_c="$2"

newline="$(printf '\n')"
IFS="$newline"
while read line; do
    case "$line" in
    '#define OP_'*)
        IFS=" "
        set -- $line
        IFS="$newline"
        name="${2#OP_}"
        i="$3"
        eval "ARRAY_label_$i=\"$name\""
        if [ "$mx" -lt "$i" ]; then
            mx="$i"
        fi
        ;;
    esac
done < "$opcodes_h"

i=0
while [ "$i" -le "$mx" ]; do
    eval "label=\"\$ARRAY_label_$i\""
    printf '    /* %3d */ "%s",\n' "$i" "$label"
    i=$((i + 1))
done
printf '%s\n' "  };"
printf '%s\n' "  return azName[i];"
printf '%s\n' "}"

# Scan the vdbe.c file for the "Synopsis:" and "Predicates:" entries of each
# opcode and make the function that selects the synopsis of an instruction.
#
# An opcode has at most one "Synopsis:" entry. Its value is on the same
# line, or it is a list with one item, which starts with "-", on each of
# the next lines:
#
#       /* Opcode: Variable P1 P2 * P4 *
#        * Predicates:
#        * - NO_NAME: P4.z == NULL
#        * Synopsis:
#        * - {{ NO_NAME }} r[P2] = parameter(P1)
#        * -               r[P2] = parameter(P1, P4)
#
# An item of "Synopsis:" can start with a predicate in "{{ ... }}". The
# first item with a true predicate is the synopsis of the instruction. The
# last item has no predicate: it is the default one.
#
# An item of "Predicates:" is a named predicate, a C macro that the
# predicates in "{{ ... }}" of this opcode can use: its name, then ":",
# and then its text. "Predicates:" comes before "Synopsis:".
#
# A predicate in "{{ ... }}" and the text of a named predicate are C
# expressions. These names are replaced in them:
#
#       P1, P2, P3, P4, P5   the operand of the instruction
#       OBJ_NAME             true if the instruction has a comment that is
#                            the name of an object
#
# In the text of a synopsis, OBJ_NAME is that name.

die() {
    printf '%s\n' "mkopcodec.sh: $*" >&2
    exit 1
}

# Replace the names of the operands in a C expression.
# The operand rule runs twice: operands can be next to each other.
translate() {
    printf '%s\n' "$1" | sed -E \
        -e 's/(^|[^A-Za-z0-9_])OBJ_NAME([^A-Za-z0-9_]|$)/\1has_obj_name\2/g' \
        -e 's/(^|[^A-Za-z0-9_])P([1-5])([^A-Za-z0-9_]|$)/\1pOp->p\2\3/g' \
        -e 's/(^|[^A-Za-z0-9_])P([1-5])([^A-Za-z0-9_]|$)/\1pOp->p\2\3/g'
}

# Remove the spaces at the start of $x. The items are aligned with spaces.
ltrim() {
    while true; do
        case "$x" in
        ' '*) x=${x# } ;;
        *) break ;;
        esac
    done
}

# Start the code of the current opcode, if it is not there yet.
start_op() {
    if [ -z "$currentOp" ]; then
        die "an entry is not in the comment of an opcode: $line"
    fi
    if [ -z "$isStarted" ]; then
        printf '  case OP_%s:\n' "$currentOp"
        isStarted=1
    fi
}

# Add a named predicate of the current opcode. $x is the item.
add_predicate() {
    start_op
    if [ -n "$hasSynopsis" ]; then
        die "OP_$currentOp has predicates after the synopsis"
    fi
    ltrim
    case "$x" in
    *': '*) ;;
    *) die "OP_$currentOp has a predicate without a name: $x" ;;
    esac
    macro=${x%%': '*}
    case "$macro" in
    *[!A-Za-z0-9_]*) die "OP_$currentOp has a bad predicate name: $macro" ;;
    esac
    x=${x#*': '}
    ltrim
    printf '#define %s (%s)\n' "$macro" "$(translate "$x")"
    predicates="$predicates $macro"
}

# Add a synopsis of the current opcode. $x is the item.
add_synopsis() {
    start_op
    if [ -n "$hasDefault" ]; then
        die "OP_$currentOp has a synopsis after the default one"
    fi
    ltrim
    case "$x" in
    '{{ '*' }} '*)
        predicate=${x#'{{ '}
        predicate=${predicate%%' }} '*}
        x=${x#*' }} '}
        ltrim
        printf '    if( %s ) return "%s";\n' "$(translate "$predicate")" "$x"
        ;;
    *)
        printf '    return "%s";\n' "$x"
        hasDefault=1
        ;;
    esac
}

# Finish the code of the current opcode, if there is one.
finish_op() {
    if [ -n "$isStarted" ] && [ -z "$hasDefault" ]; then
        die "OP_$currentOp has no default synopsis"
    fi
    IFS=" "
    for name in $predicates; do
        printf '#undef %s\n' "$name"
    done
    IFS="$newline"
}

printf '%s\n' "const char *sqlOpcodeSynopsis(const struct VdbeOp *pOp, bool has_obj_name){"
printf '%s\n' "  (void)has_obj_name;"
printf '%s\n' "  switch( pOp->opcode ){"
currentOp=""
isStarted=""
hasSynopsis=""
hasDefault=""
predicates=""
section=""
while read line; do
    case "$line" in
    ??' Opcode: '*)
        finish_op
        IFS=" "
        set -- $line
        IFS="$newline"
        currentOp="$3"
        isStarted=""
        hasSynopsis=""
        hasDefault=""
        predicates=""
        section=""
        ;;
    ??' Predicates:')
        section="predicates"
        ;;
    ??' Synopsis:' | ??' Synopsis: '*)
        if [ -n "$hasSynopsis" ]; then
            die "OP_$currentOp has more than one Synopsis entry"
        fi
        x=${line#??' Synopsis:'}
        ltrim
        if [ -n "$x" ]; then
            add_synopsis
            section=""
        else
            section="synopsis"
        fi
        hasSynopsis=1
        ;;
    ' * - '*)
        x=${line#' * - '}
        case "$section" in
        predicates) add_predicate ;;
        synopsis) add_synopsis ;;
        esac
        ;;
    *)
        section=""
        ;;
    esac
done < "$vdbe_c"
finish_op
printf '%s\n' "  default:"
printf '%s\n' "    return \"\";"
printf '%s\n' "  }"
printf '%s\n' "}"
