#!/usr/bin/env tarantool
local test = require("sqltester")
test:plan(16)

-- The expected results are generated by PostgreSQL 14, see joinC.test of
-- SQLite. Only the joins that Tarantool supports, INNER and LEFT, are
-- ported, and "NULLS FIRST" is dropped, as NULLs come first in Tarantool
-- anyway. The tables have a primary key of their own, and the rows of t3
-- and t5 are listed rather than selected, as the UNION of columns with
-- NULLs is of type SCALAR, which does not fit an INTEGER column.
test:execsql([[
    DROP TABLE IF EXISTS t1;
    DROP TABLE IF EXISTS t2;
    DROP TABLE IF EXISTS t3;
    DROP TABLE IF EXISTS t4;
    DROP TABLE IF EXISTS t5;
    CREATE TABLE t1(id INT PRIMARY KEY AUTOINCREMENT, a INT, b INT, c INT);
    CREATE TABLE t2(id INT PRIMARY KEY AUTOINCREMENT, a INT, b INT, d INT);
    CREATE TABLE t3(id INT PRIMARY KEY AUTOINCREMENT, a INT, b INT, e INT);
    CREATE TABLE t4(id INT PRIMARY KEY AUTOINCREMENT, a INT, b INT, f INT);
    CREATE TABLE t5(id INT PRIMARY KEY AUTOINCREMENT, a INT, b INT, g INT);
    INSERT INTO t1(a, b, c) VALUES(11,21,31),(12,22,32),(15,25,35),(17,27,37);
    INSERT INTO t2(a, b, d) VALUES(12,22,32),(13,23,33),(15,25,35),(18,28,38),
                                  (NULL,NULL,36);
    INSERT INTO t4(a, b, f) VALUES(11,21,31),(13,23,33),(15,25,35),(19,29,39);
    -- t1 UNION t2 UNION t4
    INSERT INTO t3(a, b, e) VALUES(11,21,31),(12,22,32),(15,25,35),(17,27,37),
                                  (13,23,33),(18,28,38),(NULL,NULL,36),
                                  (19,29,39);
    -- t3 WHERE a>=15
    INSERT INTO t5(a, b, g) VALUES(15,25,35),(17,27,37),(18,28,38),(19,29,39);
]])

test:do_execsql_test(
    "joinC-1",
    [[
        SELECT a, t1.a, t2.a, t3.a, t4.a, t5.a
        FROM t1 INNER JOIN (
        t2 INNER JOIN (
        t3 INNER JOIN (
        t4 INNER JOIN t5 USING(a)
        ) USING(a)
        ) USING(a)
        ) USING(a)
        ORDER BY 1;
    ]], {
        -- <joinC-1>
        15, 15, 15, 15, 15, 15
        -- </joinC-1>
    })

test:do_execsql_test(
    "joinC-2",
    [[
        SELECT a, t1.a, t2.a, t3.a, t4.a, t5.a
        FROM t1 INNER JOIN (
        t2 INNER JOIN (
        t3 INNER JOIN (
        t4 LEFT JOIN t5 USING(a)
        ) USING(a)
        ) USING(a)
        ) USING(a)
        ORDER BY 1;
    ]], {
        -- <joinC-2>
        15, 15, 15, 15, 15, 15
        -- </joinC-2>
    })

test:do_execsql_test(
    "joinC-5",
    [[
        SELECT a, t1.a, t2.a, t3.a, t4.a, t5.a
        FROM t1 INNER JOIN (
        t2 INNER JOIN (
        t3 LEFT JOIN (
        t4 INNER JOIN t5 USING(a)
        ) USING(a)
        ) USING(a)
        ) USING(a)
        ORDER BY 1;
    ]], {
        -- <joinC-5>
        12, 12, 12, 12, "", "",
        15, 15, 15, 15, 15, 15
        -- </joinC-5>
    })

test:do_execsql_test(
    "joinC-6",
    [[
        SELECT a, t1.a, t2.a, t3.a, t4.a, t5.a
        FROM t1 INNER JOIN (
        t2 INNER JOIN (
        t3 LEFT JOIN (
        t4 LEFT JOIN t5 USING(a)
        ) USING(a)
        ) USING(a)
        ) USING(a)
        ORDER BY 1;
    ]], {
        -- <joinC-6>
        12, 12, 12, 12, "", "",
        15, 15, 15, 15, 15, 15
        -- </joinC-6>
    })

test:do_execsql_test(
    "joinC-17",
    [[
        SELECT a, t1.a, t2.a, t3.a, t4.a, t5.a
        FROM t1 INNER JOIN (
        t2 LEFT JOIN (
        t3 INNER JOIN (
        t4 INNER JOIN t5 USING(a)
        ) USING(a)
        ) USING(a)
        ) USING(a)
        ORDER BY 1;
    ]], {
        -- <joinC-17>
        12, 12, 12, "", "", "",
        15, 15, 15, 15, 15, 15
        -- </joinC-17>
    })

test:do_execsql_test(
    "joinC-18",
    [[
        SELECT a, t1.a, t2.a, t3.a, t4.a, t5.a
        FROM t1 INNER JOIN (
        t2 LEFT JOIN (
        t3 INNER JOIN (
        t4 LEFT JOIN t5 USING(a)
        ) USING(a)
        ) USING(a)
        ) USING(a)
        ORDER BY 1;
    ]], {
        -- <joinC-18>
        12, 12, 12, "", "", "",
        15, 15, 15, 15, 15, 15
        -- </joinC-18>
    })

test:do_execsql_test(
    "joinC-21",
    [[
        SELECT a, t1.a, t2.a, t3.a, t4.a, t5.a
        FROM t1 INNER JOIN (
        t2 LEFT JOIN (
        t3 LEFT JOIN (
        t4 INNER JOIN t5 USING(a)
        ) USING(a)
        ) USING(a)
        ) USING(a)
        ORDER BY 1;
    ]], {
        -- <joinC-21>
        12, 12, 12, 12, "", "",
        15, 15, 15, 15, 15, 15
        -- </joinC-21>
    })

test:do_execsql_test(
    "joinC-22",
    [[
        SELECT a, t1.a, t2.a, t3.a, t4.a, t5.a
        FROM t1 INNER JOIN (
        t2 LEFT JOIN (
        t3 LEFT JOIN (
        t4 LEFT JOIN t5 USING(a)
        ) USING(a)
        ) USING(a)
        ) USING(a)
        ORDER BY 1;
    ]], {
        -- <joinC-22>
        12, 12, 12, 12, "", "",
        15, 15, 15, 15, 15, 15
        -- </joinC-22>
    })

test:do_execsql_test(
    "joinC-65",
    [[
        SELECT a, t1.a, t2.a, t3.a, t4.a, t5.a
        FROM t1 LEFT JOIN (
        t2 INNER JOIN (
        t3 INNER JOIN (
        t4 INNER JOIN t5 USING(a)
        ) USING(a)
        ) USING(a)
        ) USING(a)
        ORDER BY 1;
    ]], {
        -- <joinC-65>
        11, 11, "", "", "", "",
        12, 12, "", "", "", "",
        15, 15, 15, 15, 15, 15,
        17, 17, "", "", "", ""
        -- </joinC-65>
    })

test:do_execsql_test(
    "joinC-66",
    [[
        SELECT a, t1.a, t2.a, t3.a, t4.a, t5.a
        FROM t1 LEFT JOIN (
        t2 INNER JOIN (
        t3 INNER JOIN (
        t4 LEFT JOIN t5 USING(a)
        ) USING(a)
        ) USING(a)
        ) USING(a)
        ORDER BY 1;
    ]], {
        -- <joinC-66>
        11, 11, "", "", "", "",
        12, 12, "", "", "", "",
        15, 15, 15, 15, 15, 15,
        17, 17, "", "", "", ""
        -- </joinC-66>
    })

test:do_execsql_test(
    "joinC-69",
    [[
        SELECT a, t1.a, t2.a, t3.a, t4.a, t5.a
        FROM t1 LEFT JOIN (
        t2 INNER JOIN (
        t3 LEFT JOIN (
        t4 INNER JOIN t5 USING(a)
        ) USING(a)
        ) USING(a)
        ) USING(a)
        ORDER BY 1;
    ]], {
        -- <joinC-69>
        11, 11, "", "", "", "",
        12, 12, 12, 12, "", "",
        15, 15, 15, 15, 15, 15,
        17, 17, "", "", "", ""
        -- </joinC-69>
    })

test:do_execsql_test(
    "joinC-70",
    [[
        SELECT a, t1.a, t2.a, t3.a, t4.a, t5.a
        FROM t1 LEFT JOIN (
        t2 INNER JOIN (
        t3 LEFT JOIN (
        t4 LEFT JOIN t5 USING(a)
        ) USING(a)
        ) USING(a)
        ) USING(a)
        ORDER BY 1;
    ]], {
        -- <joinC-70>
        11, 11, "", "", "", "",
        12, 12, 12, 12, "", "",
        15, 15, 15, 15, 15, 15,
        17, 17, "", "", "", ""
        -- </joinC-70>
    })

test:do_execsql_test(
    "joinC-81",
    [[
        SELECT a, t1.a, t2.a, t3.a, t4.a, t5.a
        FROM t1 LEFT JOIN (
        t2 LEFT JOIN (
        t3 INNER JOIN (
        t4 INNER JOIN t5 USING(a)
        ) USING(a)
        ) USING(a)
        ) USING(a)
        ORDER BY 1;
    ]], {
        -- <joinC-81>
        11, 11, "", "", "", "",
        12, 12, 12, "", "", "",
        15, 15, 15, 15, 15, 15,
        17, 17, "", "", "", ""
        -- </joinC-81>
    })

test:do_execsql_test(
    "joinC-82",
    [[
        SELECT a, t1.a, t2.a, t3.a, t4.a, t5.a
        FROM t1 LEFT JOIN (
        t2 LEFT JOIN (
        t3 INNER JOIN (
        t4 LEFT JOIN t5 USING(a)
        ) USING(a)
        ) USING(a)
        ) USING(a)
        ORDER BY 1;
    ]], {
        -- <joinC-82>
        11, 11, "", "", "", "",
        12, 12, 12, "", "", "",
        15, 15, 15, 15, 15, 15,
        17, 17, "", "", "", ""
        -- </joinC-82>
    })

test:do_execsql_test(
    "joinC-85",
    [[
        SELECT a, t1.a, t2.a, t3.a, t4.a, t5.a
        FROM t1 LEFT JOIN (
        t2 LEFT JOIN (
        t3 LEFT JOIN (
        t4 INNER JOIN t5 USING(a)
        ) USING(a)
        ) USING(a)
        ) USING(a)
        ORDER BY 1;
    ]], {
        -- <joinC-85>
        11, 11, "", "", "", "",
        12, 12, 12, 12, "", "",
        15, 15, 15, 15, 15, 15,
        17, 17, "", "", "", ""
        -- </joinC-85>
    })

test:do_execsql_test(
    "joinC-86",
    [[
        SELECT a, t1.a, t2.a, t3.a, t4.a, t5.a
        FROM t1 LEFT JOIN (
        t2 LEFT JOIN (
        t3 LEFT JOIN (
        t4 LEFT JOIN t5 USING(a)
        ) USING(a)
        ) USING(a)
        ) USING(a)
        ORDER BY 1;
    ]], {
        -- <joinC-86>
        11, 11, "", "", "", "",
        12, 12, 12, 12, "", "",
        15, 15, 15, 15, 15, 15,
        17, 17, "", "", "", ""
        -- </joinC-86>
    })

test:finish_test()
